"""Compaction sub-package — direct port of ``packages/coding-agent/src/core/compaction``."""

from nu_coding_agent.core.compaction.compaction import (
    DEFAULT_COMPACTION_SETTINGS,
    CompactionDetails,
    CompactionPreparation,
    CompactionResult,
    CompactionSettings,
    ContextUsageEstimate,
    CutPointResult,
    calculate_context_tokens,
    compact,
    estimate_context_tokens,
    estimate_tokens,
    find_cut_point,
    find_turn_start_index,
    generate_summary,
    get_last_assistant_usage,
    prepare_compaction,
    should_compact,
)
from nu_coding_agent.core.compaction.utils import (
    SUMMARIZATION_SYSTEM_PROMPT,
    FileOperations,
    compute_file_lists,
    create_file_ops,
    extract_file_ops_from_message,
    format_file_operations,
    serialize_conversation,
)

__all__ = [
    "DEFAULT_COMPACTION_SETTINGS",
    "SUMMARIZATION_SYSTEM_PROMPT",
    "CompactionDetails",
    "CompactionPreparation",
    "CompactionResult",
    "CompactionSettings",
    "ContextUsageEstimate",
    "CutPointResult",
    "FileOperations",
    "calculate_context_tokens",
    "compact",
    "compute_file_lists",
    "create_file_ops",
    "estimate_context_tokens",
    "estimate_tokens",
    "extract_file_ops_from_message",
    "find_cut_point",
    "find_turn_start_index",
    "format_file_operations",
    "generate_summary",
    "get_last_assistant_usage",
    "prepare_compaction",
    "serialize_conversation",
    "should_compact",
]
